apiVersion: skaffold/v3alpha1
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  #local:
  #  push: false
  googleCloudBuild:
    projectId: ticket-dev-372608
  artifacts:
    - image: us.gcr.io/ticket-dev-372608/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
